config/routes.rb
KiranDermasurge::Application.routes.draw do
  resources :faqs

  resources :testimonials

  resources :queries

  resources :pages

  resources :chatmessages

  resources :chatusers
  
  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  
  
  match '/about', to: 'static_pages#about'
  match '/acne_treatment', to: 'static_pages#acne_treatment'
  match '/scar_revision', to: 'static_pages#scar_revision'
  match '/micro_derma', to: 'static_pages#micro_derma'
  match '/peels', to: 'static_pages#peels'
  match '/photo_facial', to: 'static_pages#photo_facial'
  match '/mole_remove', to: 'static_pages#mole_remove'
  match '/botox', to: 'static_pages#botox'
  match '/facelift', to: 'static_pages#facelift'
  match '/laser_reface', to: 'static_pages#laser_reface'
  match '/body_shaping', to: 'static_pages#body_shaping'
  match '/mesotherapy', to: 'static_pages#mesotherapy'
  match '/vitiligo_surgical', to: 'static_pages#vitiligo_surgical'
  match '/vitiligo_medical', to: 'static_pages#vitiligo_medical'
  match '/hair_reduction', to: 'static_pages#hair_reduction'
  match '/hair_transplant', to: 'static_pages#hair_transplant'
  match '/hair_fall', to: 'static_pages#hair_fall'
  match '/breast_shaping', to: 'static_pages#breast_shaping'
  match '/nose_shape', to: 'static_pages#nose_shape'
  match '/dimple_creation', to: 'static_pages#dimple_creation'
  match '/genitalia', to: 'static_pages#genitalia'
  match '/ear', to: 'static_pages#ear'
  match '/whats_new', to: 'static_pages#whats_new'
  match '/our_doctors', to: 'static_pages#our_doctors'
  match '/doc_schedule', to: 'static_pages#doc_schedule'
  match '/special_offer', to: 'static_pages#special_offer'
  match '/contact', to: 'queries#new'
  match '/chatconsole', to: 'chatconsole#index'
  

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= simple_form_for(@faq) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question %>
    <%= f.input :answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<% provide(:title, 'Frequesntly Asked Questions') %>
<div class="insetBgd testimonial_banner"></div>
<hr />
<br />

<div class="row">

	<!-- end left -->
<h1>FAQ</h1>
	<section class="span12" >
		<div class="well">

			<div id="testimonials">
				
				<% @faqs.each do |faq| %>
				
				<h4>
					<p>
						<%= faq.question %>
					</p>	
				</h4>
				
				<blockquote>
					<p>
						<%= faq.answer %>
					</p>	
				</blockquote>
					<% if user_signed_in? %>
						<p class="testimonial-author">
							<span><td><%= link_to 'Edit', edit_faq_path(faq) %></td></span> | <span><td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td></span>
						</p>
					<% end %>
				<br />
				<% end %>
			</div>
		</div><!--end well -->
	</section><!--end right -->
	
	
</div>

<% if user_signed_in? %>
	<%= link_to 'New Faq', new_faq_path %>
<% end %>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/show2.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>