config/routes.rb
KiranDermasurge::Application.routes.draw do
  resources :faqs

  resources :testimonials

  resources :queries

  resources :pages

  resources :chatmessages

  resources :chatusers
  
  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  
  
  match '/about', to: 'static_pages#about'
  match '/acne_treatment', to: 'static_pages#acne_treatment'
  match '/scar_revision', to: 'static_pages#scar_revision'
  match '/micro_derma', to: 'static_pages#micro_derma'
  match '/peels', to: 'static_pages#peels'
  match '/photo_facial', to: 'static_pages#photo_facial'
  match '/mole_remove', to: 'static_pages#mole_remove'
  match '/botox', to: 'static_pages#botox'
  match '/facelift', to: 'static_pages#facelift'
  match '/laser_reface', to: 'static_pages#laser_reface'
  match '/body_shaping', to: 'static_pages#body_shaping'
  match '/mesotherapy', to: 'static_pages#mesotherapy'
  match '/vitiligo_surgical', to: 'static_pages#vitiligo_surgical'
  match '/vitiligo_medical', to: 'static_pages#vitiligo_medical'
  match '/hair_reduction', to: 'static_pages#hair_reduction'
  match '/hair_transplant', to: 'static_pages#hair_transplant'
  match '/hair_fall', to: 'static_pages#hair_fall'
  match '/breast_shaping', to: 'static_pages#breast_shaping'
  match '/nose_shape', to: 'static_pages#nose_shape'
  match '/dimple_creation', to: 'static_pages#dimple_creation'
  match '/genitalia', to: 'static_pages#genitalia'
  match '/ear', to: 'static_pages#ear'
  match '/whats_new', to: 'static_pages#whats_new'
  match '/our_doctors', to: 'static_pages#our_doctors'
  match '/doc_schedule', to: 'static_pages#doc_schedule'
  match '/special_offer', to: 'static_pages#special_offer'
  match '/contact', to: 'queries#new'
  match '/chatconsole', to: 'chatconsole#index'
  

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :email, :message, :name
  
  validates_presence_of :name, :email, :message
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :message, :maximum => 500
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
  def new
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      #format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(params[:testimonial])

    respond_to do |format|
      format.js
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render json: @testimonial, status: :created, location: @testimonial }
        
      else
        format.html { render action: "new" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonials/1
  # PUT /testimonials/1.json
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(params[:testimonial])
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= simple_form_for(@testimonial, :remote => true, :validate => true ) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
	<%= f.input :name, :placeholder => 'Please Enter Full Name' %>
	<%= f.input :email, :placeholder => 'Please Enter your Email ID' %>
	<%= f.input :message, :as => :text, :input_html => { :rows => 3 }, :placeholder => 'Please Enter your Testimonial.' %>
</div>

<div class="form-actions">
	<%= f.button :submit,'Submit Testimonial', :class => 'btn btn-normal btn-primary' %>
	<a id="testimonial-form-cancel" class="btn btn-small btn-primary" href='javascript:;' >Cancel</a>
</div>

<script>
	$('#testimonial-form-cancel').click(function(e) {
		//Close all <div> but the <div> right after the clicked <a>
		//$(e.target).next('div').siblings('div').slideUp();
		//Toggle open/close on the <div> after the <a>, opening it if not open.
		$('#testimonial_container').slideToggle(900);
		$('#new_testimonial').remove();
		$('#new_link').fadeIn(900);
	}); 
</script>

<% end %>

app/views/testimonials/_testimonial.html.erb
<blockquote class="testimonial">
	<p>
		<%= testimonial.message %>
	</p>
</blockquote>
<div class="arrow-down"></div>
<p class="testimonial-author">
	<%= testimonial.name %> | <span><%= mail_to testimonial.email %></span> 
	| <span><td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td></span> | <span><td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td></span>
</p>
<br />

app/views/testimonials/create.js.erb
$('#testimonial_container').slideToggle(900);
$('#new_testimonial').remove();
$('#new_link').fadeIn(900);
$('#testimonials').append('<%= j render(@testimonial) %>');

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<% provide(:title, 'Testimonials') %>
<div class="insetBgd testimonial_banner"></div>
<hr />
<br />

<div class="row">

	<!-- end left -->

	<section class="span7" >
		<div class="well">

			<div id="testimonials">
				<h3>Testimonials</h3>
				<% @testimonials.each do |testimonial| %>
				<blockquote class="testimonial">
					<p>
						<%= testimonial.message %>
					</p>
				</blockquote>
				<div class="arrow-down"></div>
				<p class="testimonial-author">
					<%= testimonial.name %> | <span><%= mail_to testimonial.email %></span>
					<% if user_signed_in? %>
						| <span><td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td></span> | <span><td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td></span>
					<% end %>
				</p>
				<br />
				<% end %>
			</div>
		</div><!--end well -->
	</section><!--end right -->
	
	<section class="span5" style='text-align: center;'>
		<br />

		<br />

		<%= link_to 'Write a Testimonial ?', new_testimonial_path, id: "new_link", :remote => true, :class => 'btn btn-large btn-primary' %>

		<div id="testimonial_container" style='display: none; border-style:solid; border-width:1px; border-color: #5c5c9e'>

		</div>

		<br class="clear">

	</section>
</div>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/new.js.erb
$('#new_link').hide();

$('#testimonial_container').append('<%= j render("form")%>');
$('#testimonial_container').slideToggle();
$('form[data-validate]').validate();

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimonial.name %>
</p>

<p>
  <b>Email:</b>
  <%= @testimonial.email %>
</p>

<p>
  <b>Message:</b>
  <%= @testimonial.message %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>