config/routes.rb
KiranDermasurge::Application.routes.draw do
  resources :faqs

  resources :testimonials

  resources :queries

  resources :pages

  resources :chatmessages

  resources :chatusers
  
  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  
  
  match '/about', to: 'static_pages#about'
  match '/acne_treatment', to: 'static_pages#acne_treatment'
  match '/scar_revision', to: 'static_pages#scar_revision'
  match '/micro_derma', to: 'static_pages#micro_derma'
  match '/peels', to: 'static_pages#peels'
  match '/photo_facial', to: 'static_pages#photo_facial'
  match '/mole_remove', to: 'static_pages#mole_remove'
  match '/botox', to: 'static_pages#botox'
  match '/facelift', to: 'static_pages#facelift'
  match '/laser_reface', to: 'static_pages#laser_reface'
  match '/body_shaping', to: 'static_pages#body_shaping'
  match '/mesotherapy', to: 'static_pages#mesotherapy'
  match '/vitiligo_surgical', to: 'static_pages#vitiligo_surgical'
  match '/vitiligo_medical', to: 'static_pages#vitiligo_medical'
  match '/hair_reduction', to: 'static_pages#hair_reduction'
  match '/hair_transplant', to: 'static_pages#hair_transplant'
  match '/hair_fall', to: 'static_pages#hair_fall'
  match '/breast_shaping', to: 'static_pages#breast_shaping'
  match '/nose_shape', to: 'static_pages#nose_shape'
  match '/dimple_creation', to: 'static_pages#dimple_creation'
  match '/genitalia', to: 'static_pages#genitalia'
  match '/ear', to: 'static_pages#ear'
  match '/whats_new', to: 'static_pages#whats_new'
  match '/our_doctors', to: 'static_pages#our_doctors'
  match '/doc_schedule', to: 'static_pages#doc_schedule'
  match '/special_offer', to: 'static_pages#special_offer'
  match '/contact', to: 'queries#new'
  match '/chatconsole', to: 'chatconsole#index'
  

end

app/views/layouts/_doctors_know_more.html.erb
<div id="dr_kiran" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Kiran Dhar</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - PG Degree in Dermatology
		</p>
		<p>
			<strong>Institute </strong> - College of Medicine, Wales, UK
		</p>
		<p>
			<strong>Designation</strong> - Consultant Dermatologist
		</p>

		<p>
			Dr. Kiran Dhar is an experienced  dermatologist motivated by her motto of honesty, integrity and service in medical practice. Currently,
			she is practicing in Dubai after building her reputation as a skin specialist and a cosmetic practitioner. She is respected and well known
			for her laser treatments, anti aging and skin rejuvenation programmes in the Arab Gulf.
		</p>

		<p>
			Following her Postgraduate degree in dermatology from the College of Medicine, Wales, UK, Dr. Kiran received intensive training in cutaneous
			surgery in San Diego, University college of Medicine, California, USA. She built up her expertise in laser training from prestigious
			institutions in the US and Italy. Her special interest in phototherapy took her to hospitals in UK and Germany where she received
			extensive training in various aspects of phototherapy.
		</p>

		<p>
			Dr Kiran is also a Fellow of the American Academy of Dermatology.
		</p>
		<p>
			Dr KiranDhar aspires to share her expertise and contribute her services in the promotion of dermatology in her home country, India.
		</p>

	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_aditi_jha" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Aditi Jha</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS (AIIMS) MD (AIIMS)
		</p>
		<p>
			<strong>Designation</strong> - Consultant Dermatologist
		</p>

		<p>
			Dr. Aditi Jha is a refined dermatologist and has to her credit the management of difficult and interesting cases in Clinical 													 											Dermatology, Venereology, Dermatosurgery, Lasers and cosmetology from  the premier institute of the country (AIIMS, New Delhi).
			Her ongoing interest in academics has led her to attend and actively participate in all the conferences and meets.
			She is life member of the Indian Association of Dermatology, venereology and leprology.
		</p>

		<p>
			Her field of research is in psychosocial aspects of skin diseases and vitiligo (leucoderma). She has gained a vast experience
			in clinical dermatology, dermatosurgery, lasers, chemical peels during her residency in AIIMS. Her areas of interest includes clinical  		 											drmatovenereology, vitiligo surgery, chemical peels and lasers.
		</p>

	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_chanchal" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Chanchal Choudhary</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Designation</strong> - Consultant Dermatologist
		</p>

		<p>
			Dr. Chanchal Choudhary is currently working as a Consultant in kirandermasurge, Max hospital, Panchsheel. She has a five years of experience in the field of Dermatology. Her areas of expertise and special interests include - Chemical peels, microdermabrasion (skin polishing), radiofrequency procedures, cryosurgery, collagen induction therapies, botox ,fillers, mesotherapy, scar treatments, vitiligo (leucoderma) surgery, nail surgery, and lasers for various indications.
		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_naresh" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Naresh Jain</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS MD (PGI, Chandigarh), Ex Senior resident (AIIMS, New Delhi)
		</p>
		<p>
			<strong>Designation</strong> - Consultant Dermatologist, Dermatosurgeon & Cosmetologist
		</p>

		<p>
			Dr. Naresh Jain has a rare distinction of having five and half years ofexperience in Clinical Dermatology, Venereology, Dermatosurgery, Lasers and cosmetology from both the premier institutes of the country (PGI, Chandigarh and AIIMS, New Delhi).
		</p>

		<p>
			Because of his interest in academics, updating his knowledge and sharpening his skills, he regularly attends all state, national and international conferences. He is life member of all the national and international Dermatology, Dermatosurgery , Cosmetology and Hair societies/associations.
		</p>

		<p>
			He is the first recipient of Cosmetic society of India (CSI) scholarship to present and attend world congress of Dermatology (WCD 2011) held in Seoul, South Korea. He recently got scholarship to attend and present a paper at International summer academy 2011 in Munich, Germany. Dr Naresh Jain has got prestigious fellowship at National Skin Centre , Singapore for 2012 in in Lasers and Cosmetology.
		</p>

		<p>
			His field of research is in atopic dermatitis and Vitiligo (leucoderma). In clinical dermatology his interest areas are pediatricdermatoses, management of resistant acne and melasma. During his stint at PGI, Chandigarh as junior resident and at AIIMS, New Delhi as senior resident he not only gained vast experience in managing difficult dermatology problems but also did a lot of work in dermatosurgery , Lasers,Microdermabrasion, Chemical peeling, Microneedling, Botox , and Fillers.

		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_neha" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Neha Garg</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS
		</p>
		<p>
			<strong>Institute</strong> - Sardar Patel Medical College, Bikaner
		</p>
		<p>
			<strong>Designation</strong> - Cosmetologist
		</p>

		<p>
			Dr. Neha Garg is an alumini of Sardar Patel Medical college, Bikaner. She has been a Family Physician withmore than 22 years of experience. She has been actively involved in providing primary health care and promoting community health care activities.
		</p>

		<p>
			She is associated with various non governmental organizations that offer healthcare to the mother child. She is proficient in cosmetology and keeps on actively updating her knowledge and skills by regularly attending various cosmetology conferences and workshops. Her areas of special interest include Lasers and antiaging treatments.
		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_sheilly" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Sheilly Kapoor</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS, MD ( Dermatology and Venereology)
		</p>
		<p>
			<strong>Institute</strong> - Medical College, Patiala
		</p>
		<p>
			<strong>Designation</strong> - Consultant Dermatologist & Cosmetologist
		</p>

		<p>
			Visiting Consultant at Medanta Medicity Hospital , Gurgaon.
		</p>
		<p>
			Dr. Sheilly Kapoor has contributed immenselythe field of Dermatology for the past 13 years with a special interest in Dermatosurgery and Cosmetology . She has to her credit a detailed microbiological & clinical study related to 'Nails.' Treating acne scars remains a special area of interest.
		</p>

		<p>
			Following her Post graduation in the field of Dermatology and Venereology from Medical College , Patiala, she has done elaborate works and has attended many national and international conferences and has presented many papers on her work .
		</p>
		<p>
			Besides teaching undergraduate and postgraduate students , she loves attending various workshops, health melasand short training programmes aimed at disseminating information to the layman and ameliorating his life.
		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_pooja" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Pooja Aggarwal</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS, MD ( Dermatology )
		</p>

		<p>
			Dr Pooja Aggarwal has a rich experience as a dermatologist, trichologist, dermatosurgeon and cosmetologist. She was initially associated with Artemis Hospital and Kaya Skin Clinic in Gurgaon. Currently, she is associated with Kiran Dermasurge.
		</p>
		<p>
			She is an alumini of the prestigious All India Institute of Medical Sciences which has the best dermatology department in India. She has superior diagnostic skills and treatment abilities which are in best interest of patients. She deals with all kinds of skin, hair and nail issues.  She has managed difficult cases of clinical dermatology. Her urge to update her on latest development has led her to attend different seminars and conferences. . She has some publications to her credit in the field of vasculitis and adverse drug reactions.
		</p>
		<p>
			She is experienced in laser hair reduction, chemical peels, microdermabrasion, photofacial, fractional laser, dermaroller, mesotherapy, radiocautery, mole removal, ear lobe repair, phototherapy, vitiligo surgeries, Botox, Fillers amongst others

		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>


<div id="dr_sid" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Sidharth Sonthalia</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS (Hons.), MD, DNB, MNAMS
		</p>
		<p>
			<strong>Designation</strong> - Consultant Dermatologist, Dermatosurgeon & Cosmetologist
		</p>

		<p>
			Following his MBBS (with Honours), Dr. Sidharth Sonthalia pursued his MD in Dermatology and Venereology in 2008. In a short span of 6 years in dermatology, he presented his papers at various national and international conferences that won him international recognition. His research paper at the 10th International Congress of Dermatology at Prague (Czech Republic) in 2009 and was the recipient of International Society of Dermatology (ISD) travel fellowship award for the same. He has also presented his research paper at the World Congress of Dermatology at Seoul (South Korea) in May 2011 and was awarded the CSIR travel grant for the same. He has recently been awarded the Imrich-Sarkany Scholarship 2011 from the European Academy of Dermatology and Venereology (EADV) to attend the annual EADV conference at Lisbon, Portugal in October 2011.
</p>
		<p>
Dr.Sonthalia undertook the "International Society of Dermatology (ISD) Fellowship in Dermatosurgery& Cosmetology" in Tehran. It was a scholarship-cum-fellowship awarded by ISD, a rare distinction which very few Indian dermatologists have got so far. The procedures in which he received specialized training in the fellowship included - lasers, botulinum toxin, fillers, hair transplantation and liposuction.
</p>
		<p>
Apart from being a life member of IADVL, Dr.Sonthalia is also a member of ISD and member of the Executive Committee of IADVL-Delhi State Branch. He has many journal publications to his credit and has contributed chapters to various dermatology books for post-graduate as well undergraduate training in dermatology. He is currently the Assistant Editor of Journal of Cutaneous & Aesthetic Surgery. 
		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

<div id="dr_dilip" class="modal hide fade in large" data-backdrop="static" style="display: none;">

	<div class="modal-header">
		<h3>Dr. Dilip Meena</h3>
	</div>
	<div class="modal-body" style="text-align: justify;">
		<p>
			<strong>Qualification</strong> - MBBS- Bachelor of Medicine and Surgery- SMS Medical college, Jaipur, India
			<br />
			MD (Dermatology)- All India Institute of Medical Sciences, New Delhi India.
		</p>
		<p>
			<strong>Publications</strong> - Published in Indian journal of Dermatology
			<br />Has done thesis in aquired palmoplantar plaques.
		</p>
		<p>
		<strong>Dr. Dilip</strong> has completed his MBBS from SMS Medical college, jaipur and MD in
		Dermatology,  venereology and leprology from prestigious All india institute of medical science of New Delhi in 2009.
		</p>
		<p>
		He has vast experience in the field of cosmetic dermatological procedures and lasers, Hair transplant and Hair rejuvenation ( PRP and Mesotherapy).
		</p>
		<p>
		He is well experienced in CO2 Lasers, ND YAG lasers, Diode lasers etc. He is well trained in cosmetic dermatology including chemical peels, radiofrquency cautery, acne scar surgeries, botox and vitiligo surgery.
		
		He was previously associated with kaya skin clinic, karol bagh and City skin centre. 
		</p>
	</div>

	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Close</a>
	</div>

</div>

app/views/layouts/_footer.html.erb
<footer>
	<div style="width: 25%; float: left; margin-top:18px;">
		<%= link_to image_tag("facebook.png", alt: "kirandermasurge facebook page", border: "0"), "https://www.facebook.com/kiranderma", :class => 'footer_logo' %>
		<%= link_to image_tag("twitter.png", alt: "kirandermasurge twitter page", border: "0"), "http://twitter.com/KiranDerma", :class => 'footer_logo' %>
		
		<%= link_to image_tag("//ssl.gstatic.com/images/icons/gplus-32.png", alt: "kirandermasurge Google+ page", border: "0"), "//plus.google.com/113240898052101591436?prsrc=3", :class => 'footer_logo' %>
		
		<%= link_to image_tag("//s.ytimg.com/yt/img/creators_corner/YouTube/youtube_32x32.png", alt: "kirandermasurge Google+ page", border: "0"), "http://www.youtube.com/user/kirandermasurge", :class => 'footer_logo' %>
	<small> Made by Pranav Dhar</a>. Contact: <a href="mailto:pranav.dhar2@gmail.com">pranav.dhar2@gmail.com</a>. </small>	
	</div>
	<br/>
	
	<nav>
		<ul>
			<li>
				<practo:abs_widget widget="c2f832108f756aa5"></practo:abs_widget>
				<script src="https://www.practo.com/bundles/practopractoapp/js/abs_widget_helper.js"></script>
				<script>
					$(".practo_link").remove();
				</script>
			</li>
			<li class="footer_button">
				<%= link_to "About",   about_path %>
			</li>
			<li class="footer_button">
				<%= link_to "Blog",   "http://kirandermatekniks.blogspot.in/" %>
			</li>
			<li class="footer_button">
				<%= link_to "Contact Us", contact_path %>
			</li>
			<li class="footer_button">
				<%= link_to "FAQ", faqs_path %>
			</li>
			<!--li><a href="http://news.railstutorial.org/">News</a></li-->
		</ul>
	</nav>
</footer>


app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container" valign="center">

			<!--<%= link_to "kiran dermasurge", root_path, id: "logo" %>-->
			<%= link_to image_tag("kds_logo_new.jpg", alt: "kirandermasurge logo", border: "0"), root_path, id: "logo", :class => 'brand' %>

			<nav>
				<ul class="nav pull-left">
					<!-- Services,  Out Doctor, What's New, Media, Testimonial, FAQ's , Contact-->

					<li class="dropdown">
						<a data-toggle="dropdown" class="dropdown-toggle" href="#">Services <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="dropdown-submenu">
								<a href="#">Skin Rejuvenation</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Acne Treatment", acne_treatment_path %>
									</li>
									<li>
										<%= link_to "Scar Revision", scar_revision_path %>
									</li>
									<li>
										<%= link_to "Microdermabration", micro_derma_path %>
									</li>
									<li>
										<%= link_to "Peels", peels_path %>
									</li>
									<li>
										<%= link_to "Photo Facial", photo_facial_path %>
									</li>
									<li>
										<%= link_to "Skin tags/moles/warts removal", mole_remove_path %>
									</li>
								</ul>
							</li>
							<li class="dropdown-submenu">
								<a href="#">Anti Aging</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Botox / Filler", botox_path %>
									</li>
									<li>
										<%= link_to "Face Lift", facelift_path %>
									</li>
									<li>
										<%= link_to "Laser Resurfacing", laser_reface_path %>
									</li>
								</ul>
							</li>

							<li class="dropdown-submenu">
								<a href="#">Body Contouring</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Body Shaping", body_shaping_path %>
									</li>
									<li>
										<%= link_to "Mesotherapy", mesotherapy_path %>
									</li>
									<!--li>
									<a href="#">Liposuction</a> Doesn't Exist Yet!!!
									</li-->
								</ul>
							</li>
							<!--li class="divider"></li-->
							<!--li class="nav-header">Nav header</li-->
							<li class="dropdown-submenu">
								<a href="#">Vitiligo Treatment</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Surgical", vitiligo_surgical_path %>
									</li>
									<li>
										<%= link_to "Medical", vitiligo_medical_path %>
									</li>
								</ul>
							</li>
							<li>
								<%= link_to "Hair Reduction", hair_reduction_path %>
							</li>
							<li class="dropdown-submenu">
								<a href="#">Hair Treatment</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Hair Transplant", hair_transplant_path %>
									</li>
									<li>
										<%= link_to "Hair Fall Treatment", hair_fall_path %>
									</li>
								</ul>
							</li>
							<li class="dropdown-submenu">
								<a href="#">Surgeries</a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Breast", breast_shaping_path %>
									</li>
									<li>
										<%= link_to "Nose Shape Correction", nose_shape_path %>
									</li>
									<li>
										<%= link_to "Dimple Creation", dimple_creation_path %>
									</li>
									<li>
										<%= link_to "Genital Surgeries", genitalia_path %>
									</li>
									<!--li> Dead Link
									<a href="#">G-Spot Enhancement</a>
									</li-->
									<li>
										<%= link_to "Ear", ear_path %>
									</li>
								</ul>
							</li>
						</ul>
					</li>
					<li class="divider-vertical"></li>
					<li>
						<a data-toggle="modal" href="#locations">Locations</a>
					</li>

					<li class="divider-vertical"></li>
					<li>	
						<%= link_to "What's New", whats_new_path %>		
					</li>
					<li class="divider-vertical"></li>

					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Our Doctors <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Doctor's Schedule", doc_schedule_path %>
							</li>
							<li>
								<%= link_to "Know our Doctors", our_doctors_path%>
							</li>
						</ul>

					</li>
					<li class="divider-vertical"></li>
					<li>
						<%= link_to "Testimonials", testimonials_path %>
					</li>

				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>

					<!--li>
					<div class="btn-group">
					<a href="/users/sign_in" class="btn btn-small btn-primary">Sign in</a>
					</div>
					</li-->
					<% if user_signed_in? %>
					<li>
						<div class="btn-group">
							<a class="btn btn-primary" href="#"><i class="icon-user icon-white"></i>&nbsp; <%= current_user.username %> </a>
							<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
							<ul class="dropdown-menu">

								<li>

									<%= link_to raw("<i class=\"icon-wrench icon-black\"></i>&nbsp;Settings"),
									edit_user_registration_path %>
								</li>
								<!--li>
								<a href="#"><i class="icon-trash"></i> Settings</a>
								</li-->
								<li class="divider"></li>
								<li>
									<%= link_to raw("<i class=\"icon-off icon-black\"></i>&nbsp;Sign out"),
									destroy_user_session_path, method: "delete" %>
								</li>
							</ul>
						</div>
					</li>

					<% else %>
					<li>
						<% if !current_page?(new_user_session_path) %>
						<div class="btn-group">
							<%= link_to "Sign in", new_user_session_path, :class => 'btn btn-primary' %>
						</div>
						<% end %>
					</li>
					<li>
						<% if current_page?(new_user_session_path) %>
						<div class="btn-group">
							<%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary' %>
						</div>

						<% end %>
					</li>
					<% end %>

				</ul>

			</nav>
		</div>
	</div>

	<script type="text/javascript">
		//Required to initialize the dropdown menu
		$(function() {
			$('.dropdown-toggle').dropdown();
		});
	</script>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->